name: dental_guard_flutter
description: "Dental Guard Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.1.9+101099001

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.4.0
  package_info_plus: ^8.0.1
  dio: ^5.8.0+1
  http: ^1.3.0

  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

  shared_preferences: ^2.5.3
  collection: ^1.19.1
  permission_handler: ^12.0.0+1
  path_provider: ^2.1.5
  share_plus: ^11.0.0
  url_launcher: ^6.3.1

  flutter_screenutil: ^5.8.4
  flutter_svg: ^2.0.17
  intl: ^0.20.2
  signature: ^6.0.0
  cupertino_icons: ^1.0.8
  audioplayers: ^6.4.0
  camera: ^0.11.1
  image: ^4.5.4
  flutter_timezone: ^4.1.1

  fl_chart: ^1.0.0
  syncfusion_flutter_gauges: ^29.2.7+1
  syncfusion_flutter_charts: ^29.2.7

  riverpod: ^2.6.1
  flutter_riverpod: ^2.6.1
  flutter_hooks: ^0.20.0
  hooks_riverpod: ^2.6.1
  auto_route: ^10.0.1

  flutter_line_sdk: ^2.5.2
  google_sign_in: ^6.3.0

  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  firebase_crashlytics: ^4.3.6
  firebase_analytics: ^11.4.6

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.15

  freezed: ^2.4.4
  json_serializable: ^6.8.0

  path: ^1.9.0
  riverpod_generator: ^2.6.1
  auto_route_generator: ^10.0.1
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter:

  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/images/
    - assets/icons/
    - assets/sounds/

  fonts:
    - family: PingFangTC
      fonts:
        - asset: assets/fonts/PingFangTC/PingFangTcThin.otf
          weight: 100
        - asset: assets/fonts/PingFangTC/PingFangTcUltralight.otf
          weight: 200
        - asset: assets/fonts/PingFangTC/PingFangTcLight.otf
          weight: 300
        - asset: assets/fonts/PingFangTC/PingFangTcRegular.otf
          weight: 400
        - asset: assets/fonts/PingFangTC/PingFangTcMedium.otf
          weight: 500
        - asset: assets/fonts/PingFangTC/PingFangTcSemibold.otf
          weight: 600
    - family: NotoSansTC
      fonts:
        - asset: assets/fonts/NotoSansTC/NotoSansTcThin.ttf
          weight: 100
        - asset: assets/fonts/NotoSansTC/NotoSansTcExtraLight.ttf
          weight: 200
        - asset: assets/fonts/NotoSansTC/NotoSansTcLight.ttf
          weight: 300
        - asset: assets/fonts/NotoSansTC/NotoSansTcRegular.ttf
          weight: 400
        - asset: assets/fonts/NotoSansTC/NotoSansTcMedium.ttf
          weight: 500
        - asset: assets/fonts/NotoSansTC/NotoSansTcSemiBold.ttf
          weight: 600
        - asset: assets/fonts/NotoSansTC/NotoSansTcBold.ttf
          weight: 700
        - asset: assets/fonts/NotoSansTC/NotoSansTcExtraBold.ttf
          weight: 800
        - asset: assets/fonts/NotoSansTC/NotoSansTcBlack.ttf
          weight: 900

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
