name: dental_guard_flutter
description: "Dental Guard Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.8.4
  intl: ^0.18.1
  equatable: ^2.0.5
  uuid: ^4.4.2
  pausable_timer: ^3.1.0+3
  flutter_riverpod: ^2.5.1
  flutter_hooks: ^0.20.5
  hooks_riverpod: ^2.5.1
  flutter_easyloading: ^3.0.5
  shared_preferences: ^2.3.2
  cupertino_icons: ^1.0.6
  package_info_plus: ^8.0.1
  collection: ^1.18.0
  email_validator: ^3.0.0
  dio: ^5.5.0+1
  http: ^1.2.2
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  auto_route: ^9.0.0
  iconsax: ^0.0.8
  file_picker: ^8.0.6
  flutter_launcher_icons: ^0.13.1
  permission_handler: ^11.3.1
  dropdown_button2: ^2.3.9
#  fw_tab_bar: ^0.0.3
  get: ^4.6.5
  image_picker: ^1.1.2
  camera: ^0.10.5+3
  path_provider: ^2.1.2
  path: ^1.9.0
  image: ^4.0.17
  audioplayers: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.7
  freezed: ^2.4.4
  auto_route_generator: ^9.0.0
  json_serializable: ^6.8.0

flutter:

  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/images/
    - assets/sounds/
    - assets/others/

  fonts:
    - family: PingFangTC
      fonts:
        - asset: assets/fonts/PingFangTC/PingFangTcThin.otf
          weight: 100
        - asset: assets/fonts/PingFangTC/PingFangTcUltralight.otf
          weight: 200
        - asset: assets/fonts/PingFangTC/PingFangTcLight.otf
          weight: 300
        - asset: assets/fonts/PingFangTC/PingFangTcRegular.otf
          weight: 400
        - asset: assets/fonts/PingFangTC/PingFangTcMedium.otf
          weight: 500
        - asset: assets/fonts/PingFangTC/PingFangTcSemibold.otf
          weight: 600
    - family: NotoSansTC
      fonts:
        - asset: assets/fonts/NotoSansTC/NotoSansTcThin.ttf
          weight: 100
        - asset: assets/fonts/NotoSansTC/NotoSansTcExtraLight.ttf
          weight: 200
        - asset: assets/fonts/NotoSansTC/NotoSansTcLight.ttf
          weight: 300
        - asset: assets/fonts/NotoSansTC/NotoSansTcRegular.ttf
          weight: 400
        - asset: assets/fonts/NotoSansTC/NotoSansTcMedium.ttf
          weight: 500
        - asset: assets/fonts/NotoSansTC/NotoSansTcSemiBold.ttf
          weight: 600
        - asset: assets/fonts/NotoSansTC/NotoSansTcBold.ttf
          weight: 700
        - asset: assets/fonts/NotoSansTC/NotoSansTcExtraBold.ttf
          weight: 800
        - asset: assets/fonts/NotoSansTC/NotoSansTcBlack.ttf
          weight: 900

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
