// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-pA2Py0qSi8aiN62rqG4kFc9v9jUHyFc',
    appId: '1:143887662618:web:eb3c087924c34a0c509ba3',
    messagingSenderId: '143887662618',
    projectId: 'oralcare-4245c',
    authDomain: 'oralcare-4245c.firebaseapp.com',
    storageBucket: 'oralcare-4245c.firebasestorage.app',
    measurementId: 'G-P9NRPW0RXT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsKm6shSPqASLZAcyV-nKiEfzSeChZokQ',
    appId: '1:143887662618:android:fd2fba019663b747509ba3',
    messagingSenderId: '143887662618',
    projectId: 'oralcare-4245c',
    storageBucket: 'oralcare-4245c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMwviCSjeYURaGcWbCsfYS0dCRGTFJu0k',
    appId: '1:143887662618:ios:edc68d7ef35d29f4509ba3',
    messagingSenderId: '143887662618',
    projectId: 'oralcare-4245c',
    storageBucket: 'oralcare-4245c.firebasestorage.app',
    iosBundleId: 'com.lhr.oralcare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMwviCSjeYURaGcWbCsfYS0dCRGTFJu0k',
    appId: '1:143887662618:ios:edc68d7ef35d29f4509ba3',
    messagingSenderId: '143887662618',
    projectId: 'oralcare-4245c',
    storageBucket: 'oralcare-4245c.firebasestorage.app',
    iosBundleId: 'com.lhr.oralcare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-pA2Py0qSi8aiN62rqG4kFc9v9jUHyFc',
    appId: '1:143887662618:web:6ffc631ccf02c513509ba3',
    messagingSenderId: '143887662618',
    projectId: 'oralcare-4245c',
    authDomain: 'oralcare-4245c.firebaseapp.com',
    storageBucket: 'oralcare-4245c.firebasestorage.app',
    measurementId: 'G-57JMBP1MYS',
  );

}