// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZTifA7FMqABvJ50Vpkf0o0BT5EbGlL8M',
    appId: '1:602076142232:web:fb3033dc91d0156bcb8eed',
    messagingSenderId: '602076142232',
    projectId: 'dental-guard-d0786',
    authDomain: 'dental-guard-d0786.firebaseapp.com',
    storageBucket: 'dental-guard-d0786.firebasestorage.app',
    measurementId: 'G-5ZBKXNJZ0P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDLHkdk8KjoMuu2WJFLTUQJCTtIYgCc54',
    appId: '1:602076142232:android:d0a8edc2794c55a7cb8eed',
    messagingSenderId: '602076142232',
    projectId: 'dental-guard-d0786',
    storageBucket: 'dental-guard-d0786.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnk6QSSO-b1Cv5LB2BkkwqKUwZoBkiUPs',
    appId: '1:602076142232:ios:9948481323e2e058cb8eed',
    messagingSenderId: '602076142232',
    projectId: 'dental-guard-d0786',
    storageBucket: 'dental-guard-d0786.firebasestorage.app',
    iosBundleId: 'com.lhr.dentalGuardFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnk6QSSO-b1Cv5LB2BkkwqKUwZoBkiUPs',
    appId: '1:602076142232:ios:9948481323e2e058cb8eed',
    messagingSenderId: '602076142232',
    projectId: 'dental-guard-d0786',
    storageBucket: 'dental-guard-d0786.firebasestorage.app',
    iosBundleId: 'com.lhr.dentalGuardFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZTifA7FMqABvJ50Vpkf0o0BT5EbGlL8M',
    appId: '1:602076142232:web:c9d8ce0f7fbc88fbcb8eed',
    messagingSenderId: '602076142232',
    projectId: 'dental-guard-d0786',
    authDomain: 'dental-guard-d0786.firebaseapp.com',
    storageBucket: 'dental-guard-d0786.firebasestorage.app',
    measurementId: 'G-Q1EJQF81Q6',
  );
}
